filename:
  data/241025 Unicredit Macro & Markets Weekly Focus - python.pdf

data_page:
  3

multiple_label_merge_strategy:
  collapse

schemas:
  - name: date
    dtype: datetime-2024
    rename_col: True